const DATABASE = {
  "SGGW(w trakcie dodawania)": [],
  "Jedzenie i picie": ["Pizza", "Bimber", "Sushi", "Hamburger", "Spaghetti", "Lody", "Pierogi", "Kebab", "Arbuz", "Truskawka", "Brokuł", "Makaron", "Pomidorowa", "Coca-cola", "Ser", "Herbata", "Kawa", "Matcha", "Kakao", "Kompot", "Masło", "Miód", "Cynamon", "Szarlotka", "Nachosy", "Popcorn", "Rosół", "Whiskey", "Wódka", "Piwo", "Woda", "Cebularz", "Brownie", "Croissant", "Bułka z masłem", "Żurek", "Bigos", "Schabowy", "Kotlet mielony", "Gofry", "Naleśniki", "Pączek"],
  "Filmy": ["Titanic", "Avatar", "Gladiator", "Matrix", "Shrek", "Joker", "Interstellar", "Furioza", "Pulp Fiction", "Ojciec chrzestny", "Incepcja", "Władca Pierścieni", "Harry Potter", "Piraci z Karaibów", "Gwiezdne wojny", "Król Lew", "Frozen", "Avengers", "Spider-Man", "Batman", "Superman", "Iron Man", "Toy Story", "Jurassic Park", "Terminator", "Forrest Gump", "Zielona mila", "Siedem", "Fighter", "Whiplash", "Gladiator", "Jak wytresować smoka", "Pingwiny z Madagaskaru", "Kung Fu Panda", "Wolverine", "Thor", "Czarny Łabędź", "Incepcja", "Django", "Venom", "La La Land", "Oppenheimer"],
  "Przedmioty": ["Tłok", "Krzesło", "Stół", "Lampa", "Telefon", "Komputer", "Klawiatura", "Myszka", "Monitor", "Zeszyt", "Długopis", "Poduszka", "Koc", "Łóżko", "Szafa", "Lustro", "Zegar", "Dywan", "Zasłona", "Doniczka", "Kwiat", "Pilot", "Telewizor", "Słuchawki", "Głośnik", "Mikrofon", "Ładowarka", "Kabel", "Pendrive", "Powerbank", "Klucze", "Portfel", "Dokumenty", "Karta", "Okulary", "Etui", "Parasol", "Torba", "Walizka", "Czapka", "Kurtka", "Rękawiczki", "Skarpetki", "Buty", "Pasek", "Szalik", "Szczoteczka do zębów", "Grzebień", "Ręcznik", "Mydło"],
  "Zwierzęta": ["Papuga", "Jednorożec", "Kot", "Pies", "Słoń", "Delfin", "Orzeł", "Lew", "Pingwin", "Koala", "Ślimak", "Żyrafa", "Zebra", "Hipopotam", "Nosorożec", "Kangur", "Panda", "Niedźwiedź", "Wilk", "Lis", "Królik", "Chomik", "Żółw", "Krokodyl", "Rekin"],
  "Zawody": ["W WYCIĄGANIU CHUJA Z WODY, he he", "Lekarz", "Nauczyciel", "Strażak", "Pilot", "Kucharz", "Prawnik", "Programista", "Aktor", "Pielęgniarka", "Policjant", "Mechanik", "Elektryk", "Hydraulik", "Śmieciarz", "Kierowca autobusu", "Architekt", "Inżynier", "Dziennikarz", "Fotograf", "Fryzjer", "Sprzedawca", "Kelner", "Bibliotekarz", "Weterynarz", "Dentysta"],
  "Sport": ["Piłka nożna", "Koszykówka", "Siatkówka", "Tenis", "Tenis stołowy", "Piłka ręczna", "Pływanie", "Łucznictwo", "Skoki narciarskie", "Bieganie", "Sprint", "Rzut dyskiem", "Akrobatyka", "Karate", "Boks", "Kolarstwo", "Skoki spadochronowe", "Kulturystyka", "Siłownia", "Przysiady", "Podciąganie", "Szachy", "Warcaby", "Wspinaczka"],
  "Supermoce": ["Latanie", "Niewidzialność", "Super siła", "Super szybkość", "Teleportacja", "Czytanie w myślach", "Kontrola czasu", "Zamrażanie", "Regeneracja", "Nieśmiertelność", "Kontrola wody", "Kontrola ziemi", "Kontrola wiatru", "Lasery z oczu", "Super inteligencja", "Kontrola umysłu", "Tworzenie iluzji", "Super elastyczność"],
  "Kraje": ["Polska", "Niemcy", "Francja", "Wielka Brytania", "USA", "Meksyk", "Chiny", "Indie", "Rosja"],
  "Muzyka": ["The Beatles", "Queen", "Michael Jackson", "Madonna", "Elvis Presley", "Bob Marley", "Nirvana", "Metallica", "AC/DC", "Pink Floyd", "Led Zeppelin", "U2", "Coldplay", "Imagine Dragons", "Ed Sheeran", "Taylor Swift", "Beyoncé", "Rihanna", "Drake", "Eminem", "Dawid Podsiadło", "Sanah", "Taco Hemingway", "Doda", "Czesław Niemen", "Maryla Rodowicz", "Lady Pank", "Myslovitz", "Maanam", "Ariana Grande"],
  "Pojazdy": ["Samochód", "Rower", "Motor", "Autobus", "Tramwaj", "Pociąg", "Metro", "Samolot", "Helikopter", "Statek", "Jacht", "Łódź", "Kajak", "Żaglówka", "Poduszkowiec", "Ciężarówka", "Traktor", "Kombajn", "Czołg", "Rakieta", "Skuter", "Hulajnoga elektryczna", "Deskorolka"],
  "Miejsca": ["Zamek", "Szkoła", "Szpital", "Kościół", "Restauracja", "Kino", "Teatr", "Muzeum", "Biblioteka", "Basen", "Stadion", "Park", "Zoo", "Aquapark", "Plac zabaw", "Sklep", "Supermarket", "Apteka", "Bank", "Poczta", "Dworzec kolejowy", "Lotnisko", "Stacja benzynowa", "Hotel", "Hostel", "Camping", "Plaża", "Las", "Góry", "Jaskinia", "Most", "Tunel", "Wieża", "Ratusz", "Urząd", "Komisariat", "Straż pożarna", "Cmentarz", "Port", "Przystań", "Kawiarnia", "Pub", "Klub nocny", "Siłownia", "Warszawa", "Lodowisko", "Kręgielnia", "Escape room", "Galeria handlowa", "Parking"]
};